apiVersion: cluster.kurl.sh/v1beta1
kind: Installer
metadata:
  name: "base"
spec:
  contour:
    version: __kurl__ contourVersion __kurl__
  docker:
    additionalNoProxy: __kurl__ dockerAdditonalNoProxy __kurl__
    bypassStorageDriverWarning: __kurl__ dockerBypassStoragedriverWarning __kurl__
    dockerRegistryIP: __kurl__ dockerRegistryIP __kurl__
    hardFailOnLoopback: __kurl__ dockerHardFailOnLoopback __kurl__
    noCEOnEE: __kurl__ dockerNoCEOnEE __kurl__
    version: __kurl__ dockerVersion __kurl__
    noDocker: __kurl__ dockerNoDocker __kurl__
  fluentd:
    fullEFKStack: __kurl__ fluentdFullEFKStack __kurl__
    version: __kurl__ fluentdVersion __kurl__
  kotsadm:
    applicationNamespace: __kurl__ kotsadmApplicationNamespace __kurl__
    applicationSlug: __kurl__ kotsadmApplicationSlug __kurl__
    hostname: __kurl__ kotsadmHostname __kurl__
    uiBindPort: __kurl__ kotsadmUIBindPort __kurl__
    version: __kurl__ kotsadmVersion __kurl__
  kubernetes:
    HACluster: __kurl__ kubernetesHACluster __kurl__
    bootstrapToken: __kurl__ kubernetesBootstrapToken __kurl__
    bootstrapTokenTTL: __kurl__ kubernetesBootstrapTokenTTL __kurl__
    certKey: __kurl__ kubernetesCertKey __kurl__
    controlPlane: __kurl__ kubernetesControlPlane __kurl__
    kubeadmTokenCAHash: __kurl__ kubernetesKubeadmTokenCAHash __kurl__
    loadBalancerAddress: __kurl__ kubernetesLoadBalancerAddress __kurl__
    masterAddress: __kurl__ kubernetesMasterAddress __kurl__
    serviceCIDR: __kurl__ kubernetesServiceCIDR __kurl__
    serviceCidrRange: __kurl__ kubernetesServiceCIDRRange __kurl__
    version: __kurl__ kubernetesVersion __kurl__
  kurl:
    HTTPProxy: __kurl__ HTTPProxy __kurl__
    airgap: __kurl__ Airgap __kurl__
    bypassFirewalldWarning: __kurl__ BypassFirewalldWarning __kurl__
    hardFailOnFirewalld: __kurl__ HardFailOnFirewalld __kurl__
    hostnameCheck: __kurl__ HostnameCheck __kurl__
    noProxy: __kurl__ NoProxy __kurl__
    privateAddress: __kurl__ PrivateAddress __kurl__
    publicAddress: __kurl__ PublicAddress __kurl__
    task: __kurl__ Task __kurl__
  minio:
    namespace: __kurl__ minioNamespace __kurl__
    version: __kurl__ minioVersion __kurl__
  openEBS:
    isLocalPVEnabled: __kurl__ openEBSIsLocalPVEnabled __kurl__
    localPVStorageClassName: __kurl__ openEBSLocalPVStorageClassName __kurl__
    isCstorEnabled: __kurl__ openEBSIsCstorEnabled __kurl__
    cstorStorageClassName: __kurl__ openEBSCstorStorageClassName __kurl__
    namespace: __kurl__ openEBSNamespace __kurl__
    version: __kurl__ openEBSVersion __kurl__
  prometheus:
    version: __kurl__ prometheusVersion __kurl__
  registry:
    publishPort: __kurl__ registryPublishPort __kurl__
    version: __kurl__ registryVersion __kurl__
  rook:
    cephReplicaCount: __kurl__ rookCephReplicaCount __kurl__
    storageClassName: __kurl__ rookStorageClassName __kurl__
    version: __kurl__ rookVersion __kurl__
    isBlockStorageEnabled: __kurl__ rookIsBlockStorageEnabled __kurl__
    blockDeviceFilter: __kurl__ rookBlockDeviceFilter __kurl__
  velero:
    disableRestic: __kurl__ veleroDisableRestic __kurl__
    disableCLI: __kurl__ veleroDisableCLI __kurl__
    localBucket: __kurl__ veleroLocalBucket __kurl__
    namespace: __kurl__ veleroNamespace __kurl__
    version: __kurl__ veleroVersion __kurl__
  weave:
    isEncryptionDisabled: __kurl__ weaveisEncryptionDisabled __kurl__
    podCIDR: __kurl__ weavePodCIDR __kurl__
    podCidrRange: __kurl__ weavePodCIDRRange __kurl__
    version: __kurl__ weaveVersion __kurl__
  dockerConfig:
    authorizationPlugins: __kurl__ authorizationPlugins __kurl__
    dataRoot: __kurl__ dataRoot __kurl__
    dns: __kurl__ dns __kurl__
    dnsOpts: __kurl__ dnsOpts __kurl__
    dnsSearch: __kurl__ dnsSearch __kurl__
    execOpts: __kurl__ execOpts __kurl__
    execRoot: __kurl__ execRoot __kurl__
    experimental: __kurl__ experimental __kurl__
    features: __kurl__ features __kurl__
    storageDriver: __kurl__ storageDriver __kurl__
    storageOpts: __kurl__ storageOpts __kurl__
    labels: __kurl__ labels __kurl__
    liveRestore: __kurl__ liveRestore __kurl__
    logDriver: __kurl__ logDriver __kurl__
    logOpts: __kurl__ logOpts __kurl__
    mtu: __kurl__ mtu __kurl__
    pidFile: __kurl__ pidFile __kurl__
    clusterStore: __kurl__ clusterStore __kurl__
    clusterStoreOpts: __kurl__ clusterStoreOpts __kurl__
    clusterAdvertise: __kurl__ clusterAdvertise __kurl__
    maxConcurrentDownloads: __kurl__ maxConcurrentDownloads __kurl__
    maxConcurrentUploads: __kurl__ maxConcurrentUploads __kurl__
    defaultShmSize: __kurl__ defaultShmSize __kurl__
    shutdownTimeout: __kurl__ shutdownTimeout __kurl__
    debug: __kurl__ debug __kurl__
    hosts: __kurl__ hosts __kurl__
    logLevel: __kurl__ logLevel __kurl__
    tls: __kurl__ tls __kurl__
    tlsVerify: __kurl__ tlsVerify __kurl__
    tlsCaCert: __kurl__ tlsCaCert __kurl__
    tlsCert: __kurl__ tlsCert __kurl__
    tlsKey: __kurl__ tlsKey __kurl__
    swarmDefaultAdvertiseAddr: __kurl__ swarmDefaultAdvertiseAddr __kurl__
    apiCorsHeader: __kurl__ apiCorsHeader __kurl__
    selinuxEnabled: __kurl__ selinuxEnabled __kurl__
    usernsRemap: __kurl__ usernsRemap __kurl__
    group: __kurl__ group __kurl__
    cgroupParent: __kurl__ cgroupParent __kurl__
    defaultUlimits: __kurl__ defaultUlimits __kurl__
    init: __kurl__ init __kurl__
    initPath: __kurl__ initPath __kurl__
    ipv6: __kurl__ ipv6 __kurl__
    iptables: __kurl__ iptables __kurl__
    ipForward: __kurl__ ipForward __kurl__
    ipMasq: __kurl__ ipMasq __kurl__
    userlandProxy: __kurl__ userlandProxy __kurl__
    userlandProxyPath: __kurl__ userlandProxyPath __kurl__
    ip: __kurl__ ip __kurl__
    bridge: __kurl__ bridge __kurl__
    bip: __kurl__ bip __kurl__
    fixedCidr: __kurl__ fixedCidr __kurl__
    fixedCidrV6: __kurl__ fixedCidrV6 __kurl__
    defaultGateway: __kurl__ defaultGateway __kurl__
    defaultGatewayV6: __kurl__ defaultGatewayV6 __kurl__
    icc: __kurl__ icc __kurl__
    rawLogs: __kurl__ rawLogs __kurl__
    allowNondistributableArtifacts: __kurl__ allowNondistributableArtifacts __kurl__
    registryMirrors: __kurl__ registryMirrors __kurl__
    seccompProfile: __kurl__ seccompProfile __kurl__
    insecureRegistries: __kurl__ insecureRegistries __kurl__
    noNewPrivileges: __kurl__ noNewPrivileges __kurl__
    defaultRuntime: __kurl__ defaultRuntime __kurl__
    oomScoreAdjust: __kurl__ oomScoreAdjust __kurl__
    nodeGenericResources: __kurl__ nodeGenericResources __kurl__
    runtimes: __kurl__ runtimes __kurl__
    defaultAddressPools: __kurl__ defaultAddressPools __kurl__
  