name: build-test

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - "**"

jobs:
  build-kurl-utils:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: "1.13"

      - name: setup env
        run: |
          echo "::set-env name=GOPATH::$(go env GOPATH)"
          echo "::add-path::$(go env GOPATH)/bin"
        shell: bash

      - uses: actions/checkout@v2

      - run: go get golang.org/x/lint/golint
      - run: make -C kurl_util test build

      - uses: actions/upload-artifact@v1
        with:
          name: docker-config
          path: kurl_util/bin/docker-config
