name: deploy
on:
  push:
    tags:
    - "v*.*.*"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Unshallow
      run: git fetch --prune --unshallow

    - uses: actions/setup-go@v1
      with:
        go-version: "1.13"

    - name: set previous release tag for goreleaser
      shell: bash
      run: |
        echo ::set-env name=GORELEASER_PREVIOUS_TAG::$(curl --silent "https://api.github.com/repos/replicatedhq/kurl/releases/latest" | grep -Po '"tag_name": "\K.*?(?=")')

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v1
      working-directory: ./kurl_util
      with:
        version: latest
        args: release --rm-dist --config deploy/.goreleaser.yaml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
