name: deploy
on:
  push:
    tags:
      - "utils/*"
      - "utils-*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Unshallow
      run: git fetch --prune --unshallow

    - uses: actions/setup-go@v1
      with:
        go-version: "1.13"

    - name: setup env
      run: |
        echo "::set-env name=GOPATH::$(go env GOPATH)"
        echo "::add-path::$(go env GOPATH)/bin"
      shell: bash

    - run: go get golang.org/x/lint/golint
    - run: make -C kurl_util test build

    - uses: meeDamian/github-release@2.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ env.RELEASE_TAG }}
        files: kurl_util:./kurl_util/bin/
        prerelease: true